services:
  _defaults:
    public: true

  onlineshopmodule.module.facetedsearch.form.type.filter_item:
    class: Onlineshopmodule\PrestaShop\Module\Facetedsearch\Form\Type\FilterItemType
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

  onlineshopmodule.module.facetedsearch.form.type.filters:
    class: Onlineshopmodule\PrestaShop\Module\Facetedsearch\Form\Type\FiltersType
    parent: 'form.type.translatable.aware'
    public: true
    arguments:
      $languageId: '@=service("prestashop.adapter.legacy.context").getContext().language.id'
    tags:
      - { name: form.type }

  onlineshopmodule.module.facetedsearch.form.type.filter_template:
    class: Onlineshopmodule\PrestaShop\Module\Facetedsearch\Form\Type\FilterTemplateType
    parent: 'form.type.translatable.aware'
    public: true
    arguments:
      $multistoreFeature: '@prestashop.adapter.feature.multistore'
      $module: '@onlineshopmodule.module.facetedsearch.gc_facetedsearch'
    tags:
      - { name: form.type }
  
  onlineshopmodule.module.facetedsearch.form.identifiable_object.handler.filter_template_form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler'
    factory: [ '@prestashop.core.form.identifiable_object.handler.form_handler_factory', 'create' ]
    arguments:
      - '@onlineshopmodule.module.facetedsearch.form.identifiable_object.data_handler.filter_template_form_data_handler'

  onlineshopmodule.module.facetedsearch.form.identifiable_object.data_handler.filter_template_form_data_handler:
    class: 'Onlineshopmodule\PrestaShop\Module\Facetedsearch\Form\DataHandler\FilterTemplateFormDataHandler'
    arguments:
      $module: '@onlineshopmodule.module.facetedsearch.gc_facetedsearch'

  onlineshopmodule.module.facetedsearch.form.identifiable_object.data_provider.filter_template_form_data_provider:
    class: 'Onlineshopmodule\PrestaShop\Module\Facetedsearch\Form\DataProvider\FilterTemplateFormDataProvider'
  
  onlineshopmodule.module.facetedsearch.form.identifiable_object.builder.filter_template_form_builder:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Builder\FormBuilder'
    factory: [ '@prestashop.core.form.builder.form_builder_factory', 'create' ]
    arguments:
      - 'Onlineshopmodule\PrestaShop\Module\Facetedsearch\Form\Type\FilterTemplateType'
      - '@onlineshopmodule.module.facetedsearch.form.identifiable_object.data_provider.filter_template_form_data_provider'
